# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 14:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDolist', '0002_auto_20170901_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 9, 5, 17, 8, 23, 516582)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.date(2017, 9, 5)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 9, 5, 17, 8, 23, 516607)),
        ),
    ]
